name: dns-random-subdomains-ddos-attack 
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - jupyterlab
  - jupyter
  - tqdm
  - pyspark
  - pip:
    - datasketch
    - smart-open
    - hyperjson
